### ISSUE TITLE
Add option to disable component translation in ConnectedPlayer#sendPlayerListHeaderAndFooter

### ISSUE THREAD

**Issue by NEZNAMY** [GemstoneGG/Velocity-CTD#198]
Specifically, add option to disable these 2 lines of code:
https://github.com/GemstoneGG/Velocity-CTD/blob/43f285b4f8504abb2b539b790641a96b3c1846bf/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L447-L448

This will massively improve performance of the function.

**Comment by R00tB33rMan** [comment]
Almost entirely forgot about this. I'll make sure to get this done. Thank you!

**Comment by R00tB33rMan** [comment]
> Specifically, add option to disable these 2 lines of code:
> 
> https://github.com/GemstoneGG/Velocity-CTD/blob/43f285b4f8504abb2b539b790641a96b3c1846bf/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L447-L448
> 
> This will massively improve performance of the function.

Added in: 3aa4ae5
