### ISSUE TITLE
Bug; HEX issue with /alert

### ISSUE THREAD

**Issue by NoltoxGit** [GemstoneGG/Velocity-CTD#207]
Hello,
I've just seen that the `/alert` and `/alertraw` commands don't support the MiniMessages format for HEX colors.

Is there a way to solve this please? :)
![image](https://github.com/GemstoneGG/Velocity-CTD/assets/75265787/e54782e2-5ed1-4721-8013-09af77c0f547)

**Comment by R00tB33rMan** [comment]
> Hello, I've just seen that the `/alert` and `/alertraw` commands don't support the MiniMessages format for HEX colors.
> 
> Is there a way to solve this please? :) ![image](https://private-user-images.githubusercontent.com/75265787/329873241-e54782e2-5ed1-4721-8013-09af77c0f547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDE0MjksIm5iZiI6MTcxNTU0MTEyOSwicGF0aCI6Ii83NTI2NTc4Ny8zMjk4NzMyNDEtZTU0NzgyZTItNWVkMS00NzIxLTgwMTMtMDlhZjc3YzBmNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE5MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDVmZGIxMzg1OGVjYTMxY2M3YzhjNzQzNjhkZGE4YmJiOGZjN2Y0Nzc1OGRiNmRiZDlkNGI2NWY4MzVkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aLPuM8hgtY1GaVCMdaQfmJIn1wggBduhdOcxbXykgp0)

Strange. Can you show me the specific raw format you used in order to reproduce this issue? Can’t seem to figure out which format you’re using. Additionally, double check that you're using the latest version of Velocity-CTD.

**Comment by NoltoxGit** [comment]
> > Hello, I've just seen that the `/alert` and `/alertraw` commands don't support the MiniMessages format for HEX colors.
> > Is there a way to solve this please? :) ![image](https://private-user-images.githubusercontent.com/75265787/329873241-e54782e2-5ed1-4721-8013-09af77c0f547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDE0MjksIm5iZiI6MTcxNTU0MTEyOSwicGF0aCI6Ii83NTI2NTc4Ny8zMjk4NzMyNDEtZTU0NzgyZTItNWVkMS00NzIxLTgwMTMtMDlhZjc3YzBmNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE5MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDVmZGIxMzg1OGVjYTMxY2M3YzhjNzQzNjhkZGE4YmJiOGZjN2Y0Nzc1OGRiNmRiZDlkNGI2NWY4MzVkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aLPuM8hgtY1GaVCMdaQfmJIn1wggBduhdOcxbXykgp0)
> 
> Strange. Can you show me the specific raw format you used in order to reproduce this issue? Can’t seem to figure out which format you’re using. Additionally, double check that you're using the latest version of Velocity-CTD.

Yes sure, i'm use this version of Velocity-CTD:
![image](https://github.com/GemstoneGG/Velocity-CTD/assets/75265787/0fe8d022-c390-4bad-ae8b-3bd52d84009c)


And i use this format in the raw:
![image](https://github.com/GemstoneGG/Velocity-CTD/assets/75265787/ae3a0acb-d7a9-41b4-9632-510ba31c6039)

**Comment by R00tB33rMan** [comment]
Ah, okay, this is very much valid. I will look into structuring this in such a way that fixes various other problems with HEX under this registry. Although unnecessary, I intend also to make this sync. properly with `<color:&#XXXXXX>`, even if fully invalid.

**Comment by R00tB33rMan** [comment]
> > > Hello, I've just seen that the `/alert` and `/alertraw` commands don't support the MiniMessages format for HEX colors.
> > > Is there a way to solve this please? :) ![image](https://private-user-images.githubusercontent.com/75265787/329873241-e54782e2-5ed1-4721-8013-09af77c0f547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDE0MjksIm5iZiI6MTcxNTU0MTEyOSwicGF0aCI6Ii83NTI2NTc4Ny8zMjk4NzMyNDEtZTU0NzgyZTItNWVkMS00NzIxLTgwMTMtMDlhZjc3YzBmNTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE5MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDVmZGIxMzg1OGVjYTMxY2M3YzhjNzQzNjhkZGE4YmJiOGZjN2Y0Nzc1OGRiNmRiZDlkNGI2NWY4MzVkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aLPuM8hgtY1GaVCMdaQfmJIn1wggBduhdOcxbXykgp0)
> > 
> > 
> > Strange. Can you show me the specific raw format you used in order to reproduce this issue? Can’t seem to figure out which format you’re using. Additionally, double check that you're using the latest version of Velocity-CTD.
> 
> Yes sure, i'm use this version of Velocity-CTD: ![image](https://private-user-images.githubusercontent.com/75265787/329877194-0fe8d022-c390-4bad-ae8b-3bd52d84009c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzMwNjksIm5iZiI6MTcxNTU3Mjc2OSwicGF0aCI6Ii83NTI2NTc4Ny8zMjk4NzcxOTQtMGZlOGQwMjItYzM5MC00YmFkLWFlOGItM2JkNTJkODQwMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAzNTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYjQzZTM1YTM5MGJiZWUzNzFlMWQxYjkwMzBmNDEwNjc2YjcxNmRiZmEwYzRjYjhkNmI3ZDJkNzEyY2I0MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6wwA96iykvmrLj62KHR_MhuJmydlcUcFlZliiSRg_Do)
> 
> And i use this format in the raw: ![image](https://private-user-images.githubusercontent.com/75265787/329877234-ae3a0acb-d7a9-41b4-9632-510ba31c6039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzMwNjksIm5iZiI6MTcxNTU3Mjc2OSwicGF0aCI6Ii83NTI2NTc4Ny8zMjk4NzcyMzQtYWUzYTBhY2ItZDdhOS00MWI0LTk2MzItNTEwYmEzMWM2MDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAzNTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZjA3Yzc3MGNmNzk1OWM1ODU1OGU4NWI2OGZjMDkxMmQ0NTdmODE2NTY4ZjczM2FiMDg5NzUwYTM4OWVjYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SlCyioSG0COKEVJCn3yyEzdqlK2HIOpdSKNjxPSi3sc)

Fixed in da3f5be

**Comment by R00tB33rMan** [comment]
Just wrapped up a final keypiece to our translation method. According to extensive testing, everything now looks perfect. Thank you for reporting this!
