### ISSUE TITLE
Suggestion: Make /velocity reload, reload the messages.properties

### ISSUE THREAD

**Issue by NoltoxGit** [GemstoneGG/Velocity-CTD#211]
All in the title :)

Thank you so much if you add this!

**Comment by R00tB33rMan** [comment]
We're working on this now! Should have this done for you soon

**Comment by R00tB33rMan** [comment]
> All in the title :)
> 
> Thank you so much if you add this!

Fixed in [14c1de](https://github.com/GemstoneGG/Velocity-CTD/commit/14c1dea59e1279c243f4e2779bf5fd8dc262f0d8)!

**Comment by NoltoxGit** [comment]
test msg
