### ISSUE TITLE
cookie api issue

### ISSUE THREAD

**Issue by Dinos3396** [GemstoneGG/Velocity-CTD#267]
### Expected Behavior

Is this issue fixed on your fork?
https://github.com/PaperMC/Velocity/pull/1359

### Actual Behavior

a

### Steps to Reproduce

a

### Plugin List

a

### Velocity Version

a

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> Is this issue fixed on your fork? [PaperMC#1359](https://github.com/PaperMC/Velocity/pull/1359)
> 
> ### Actual Behavior
> a
> 
> ### Steps to Reproduce
> a
> 
> ### Plugin List
> a
> 
> ### Velocity Version
> a
> 
> ### Additional Information
> _No response_

This issue was indeed previously resolved; however, a patch was made with v4Guard that resolves this issue when processed in the configuration state. I'd encourage upgrading to v4Guard 2.5.0. If you need help compiling this version of v4Guard, feel free to let me know and I'd be happy to do so!
