### ISSUE TITLE
Velocity soft crash

### ISSUE THREAD

**Issue by MatinHQ** [GemstoneGG/Velocity-CTD#272]
### Expected Behavior

To not crash or at least throw proper error

### Actual Behavior

To not freeze

### Steps to Reproduce

I have no clue and it's no like a hard crash to throw error or anything

server will freeze and no command works and velocity does not behave (forwarding player etc..)

and it doesn't really throw any proper errors

it doesn't have any specific reproduce step sometimes it occurs around 250 player sometimes around 900 players

only thing I found interesting and was throwing 1-2 minutes before server freeze it's this
https://paste.ubuntu.com/p/GXrRzv3Z2T/

### Plugin List

Unfortunately can't share publicly due stalkers

 can share in dms

### Velocity Version

![image](https://github.com/user-attachments/assets/b80bc349-5bc5-4624-80e5-b8f0af56f51f)

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> To not crash or at least throw proper error
> 
> ### Actual Behavior
> To not freeze
> 
> ### Steps to Reproduce
> I have no clue and it's no like a hard crash to throw error or anything
> 
> server will freeze and no command works and velocity does not behave (forwarding player etc..)
> 
> and it doesn't really throw any proper errors
> 
> it doesn't have any specific reproduce step sometimes it occurs around 250 player sometimes around 900 players
> 
> only thing I found interesting and was throwing 1-2 minutes before server freeze it's this https://paste.ubuntu.com/p/GXrRzv3Z2T/
> 
> ### Plugin List
> Unfortunately can't share publicly due stalkers
> 
> can share in dms
> 
> ### Velocity Version
> ![image](https://private-user-images.githubusercontent.com/22664859/355438586-b80bc349-5bc5-4624-80e5-b8f0af56f51f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzM5MDgsIm5iZiI6MTcyMjk3MzYwOCwicGF0aCI6Ii8yMjY2NDg1OS8zNTU0Mzg1ODYtYjgwYmMzNDktNWJjNS00NjI0LTgwZTUtYjhmMGFmNTZmNTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE5NDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3OTk2MjEwZjFlNzQ1MzA3ZmNmNDdmZDk3MGJiY2NiNjJhNzgyMGU2ZjYxMjZkNzQyYmM1YjQ0OTliMjVjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._NmpO0xEDcq5EjYfiTQnwOA6YQPHJNaYQfoG9aIGaOs)
> 
> ### Additional Information
> _No response_

Shoot me a message, as this will require some debugging. I've been stably running this fork on production with over 1,100 concurrent with not a single instance of crashing. Contact me @ `.rootbeer`

**Comment by MatinHQ** [comment]
> .rootbeer

Send you a friend request my discord id is `.matin.`
