### ISSUE TITLE
Add a new command : "/uptime"

### ISSUE THREAD

**Issue by NoltoxGit** [GemstoneGG/Velocity-CTD#292]
### Requested Feature

Hello,
Would it be possible to add the `/uptime` command to find out how long the server has been online, please?

### Why is this needed?

This is useful when you're not using an interface that displays a server's uptime.

### Alternative Solutions

x

**Comment by R00tB33rMan** [comment]
Could be of consideration, as it's a relatively simple request. I'll look into doing this over the next few days!

**Comment by NoltoxGit** [comment]
> Could be of consideration, as it's a relatively simple request. I'll look into doing this over the next few days!

Would it be possible to make a `/velocity uptime` or `/vuptime` command instead, because otherwise it will overide with the PaperMC command please?

**Comment by R00tB33rMan** [comment]
> > Could be of consideration, as it's a relatively simple request. I'll look into doing this over the next few days!
> 
> Would it be possible to make a `/velocity uptime` or `/vuptime` command instead, because otherwise it will overide with the PaperMC command please?

I like to maintain some level of qualitative parity with regular Velocity. That said, I'll likely make the command `/velocity uptime`!

**Comment by R00tB33rMan** [comment]
Integrated! I tested this feature relatively thoroughly. Just like Pterodactyl (and other panels/platforms), I've supported days, hours, minutes, and seconds. I don't see a purpose in using weeks, months, or years.
