### ISSUE TITLE
Allow setting forwarding mode separately for different servers

### ISSUE THREAD

**Issue by Askarionn** [GemstoneGG/Velocity-CTD#296]
### Requested Feature

https://github.com/PaperMC/Velocity/pull/1357

### Why is this needed?

It is quite common to have a setup which includes both servers newer than 1.12 and older than 1.12. By allowing setting forwarding modes separately, we don't need to use the legacy forwarding mode all the time. Especially it is discontinued for newer fabric versions

### Alternative Solutions

-

**Comment by R00tB33rMan** [comment]
> ### Requested Feature
> 
> [PaperMC#1357](https://github.com/PaperMC/Velocity/pull/1357)
> ### Why is this needed?
> 
> It is quite common to have a setup which includes both servers newer than 1.12 and older than 1.12. By allowing setting forwarding modes separately, we don't need to use the legacy forwarding mode all the time. Especially it is discontinued for newer fabric versions
> ### Alternative Solutions
> 
> 
> ### Additional Information
> 
> _No response_

Done. Let me know if everything works accordingly!

**Comment by R00tB33rMan** [comment]
Had to drop this commit since it caused unexpected issues in other areas of user connections. I'll look into getting this thoroughly tested as soon as possible.
