### ISSUE TITLE
velocity.error.cant-connect doesn't show spigot arg:1

### ISSUE THREAD

**Issue by Askarionn** [GemstoneGG/Velocity-CTD#311]
### Expected Behavior

It should show the whitelist message
![image](https://github.com/user-attachments/assets/a8afd72b-be66-4b6a-bddf-3caad6591fc0)

### Actual Behavior

![image](https://github.com/user-attachments/assets/e8396f3d-7ddb-428e-9487-4c3f35636d3a)

### Steps to Reproduce

-

### Plugin List

tested with 0 plugins

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-bd5ff6ae)

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> It should show the whitelist message ![image](https://private-user-images.githubusercontent.com/51824859/367799359-a8afd72b-be66-4b6a-bddf-3caad6591fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDA0NzIsIm5iZiI6MTcyNjUwMDE3MiwicGF0aCI6Ii81MTgyNDg1OS8zNjc3OTkzNTktYThhZmQ3MmItYmU2Ni00YjZhLWJkZGYtM2NhYWQ2NTkxZmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNDU1NTg1NWIzZDJmNDJiZjkwMjc4ZGRmNWQwNmEyZjI4ZDk3M2MwMWM1N2IyZjRiNGZhNWI4YTI5MzkyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6xOQZPItjCnSfzsE-ebKhAcpqn_qDy8YZ9ytSFK-NYE)
> 
> ### Actual Behavior
> ![image](https://private-user-images.githubusercontent.com/51824859/367799407-e8396f3d-7ddb-428e-9487-4c3f35636d3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDA0NzIsIm5iZiI6MTcyNjUwMDE3MiwicGF0aCI6Ii81MTgyNDg1OS8zNjc3OTk0MDctZTgzOTZmM2QtN2RkYi00MjhlLTk0ODctNGMzZjM1NjM2ZDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1MjI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Y2E3NWVmNTJkOTNhNjJiMjAyNTgwMjU0MzdmYTQzZWNkNjFkYjYzOTBjZTY2YjUzN2RlNTBlMjQ4ODAxMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lul7eq7qgWqz0mn4MW8UonQiGE-iWuq5KtBGKPIcxs4)
> 
> ### Steps to Reproduce
> 
> ### Plugin List
> tested with 0 plugins
> 
> ### Velocity Version
> Velocity 3.4.0-SNAPSHOT (git-bd5ff6ae)
> 
> ### Additional Information
> _No response_

Can you provide me a raw example of your messages.properties file?

Try: https://github.com/GemstoneGG/Velocity-CTD/commit/a3e2d9eee90c404ac3e4ad3d9e28f52cf69f6555

**Comment by Askarionn** [comment]
https://pastebin.com/nYWMtXts (using the default one)
Also, I tried https://github.com/GemstoneGG/Velocity-CTD/releases/tag/Releases and it still doesn't work

**Comment by R00tB33rMan** [comment]
> https://pastebin.com/nYWMtXts (using the default one) Also, I tried https://github.com/GemstoneGG/Velocity-CTD/releases/tag/Releases and it still doesn't work

I attempted this locally and cannot reproduce this issue. Can you try on 1.21.1 or possibly older versions to see if the issue is reproducible upon all scopes?

**Comment by R00tB33rMan** [comment]
Sadly cannot reproduce this issue, even with multiple networks. You may be using an old backend architecture or something is being improperly read. If possible, attempt to find a way to make this work using the latest iteration of my fork (I did make some marginal adjustments as to how components are read). Thanks for reporting!
