### ISSUE TITLE
Not compatible with LimboAPI

### ISSUE THREAD

**Issue by ghost** [GemstoneGG/Velocity-CTD#316]
### Expected Behavior

LimboAPI doesn't work on Velocity CTD.

### Actual Behavior

LimboAPI should work on Velocity CTD.

### Steps to Reproduce

1. Install LimboAPI.
2. It won't start. 

### Plugin List

LimboAPI

### Velocity Version

3fe97fc57d4e8c93d15aa1365acaed18ee5a804a

### Additional Information

https://github.com/Elytrium/LimboAPI/issues/163

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> 
> LimboAPI doesn't work on Velocity CTD.
> ### Actual Behavior
> 
> LimboAPI should work on Velocity CTD.
> ### Steps to Reproduce
> 
>     1. Install LimboAPI.
> 
>     2. It won't start.
> 
> 
> ### Plugin List
> 
> LimboAPI
> ### Velocity Version
> 
> [3fe97fc](https://github.com/GemstoneGG/Velocity-CTD/commit/3fe97fc57d4e8c93d15aa1365acaed18ee5a804a)
> ### Additional Information
> 
> [Elytrium/LimboAPI#163](https://github.com/Elytrium/LimboAPI/issues/163)

I've provided a comment on the LimboAPI repository. Once Velocity merges this already-completed PR (based on extensive testing), LimboAPI will no longer be compatible with upstream Velocity. I'll leave this open for the time being.

**Comment by ghost** [comment]
Velocity merging this might take months, while this will be broken @R00tB33rMan

**Comment by ghost** [comment]
To follow up, I want to say that any upstream changes in Velocity lead to Limbo plugins being updated very quickly, such as [here](https://github.com/Elytrium/LimboAPI/commit/35e9eddae4e2cc318ebe7ad243f33b76668504af) or [here](https://github.com/Elytrium/LimboAPI/commit/e4526cc95f0e4171e0f087563080d4ad5e7c6a78). This won't be an issue when upstream merges this, this is an issue regarding upstream backwards compatibility right now, even though packet registration is not an API.

**Comment by Justiks1337** [comment]
this broke my plugins, that depend on velocity, this very importart for my server smp and four black pigs. Author pls fix that
![image](https://github.com/user-attachments/assets/76d313e4-9f66-4d75-91e5-42d7a2add79a)

**Comment by R00tB33rMan** [comment]
I'll look into reverting this change tomorrow (the 24th) despite its effectiveness. Hopefully, Velocity intends to merge this change sometime soon.

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> 
> LimboAPI doesn't work on Velocity CTD.
> ### Actual Behavior
> 
> LimboAPI should work on Velocity CTD.
> ### Steps to Reproduce
> 
>     1. Install LimboAPI.
> 
>     2. It won't start.
> 
> 
> ### Plugin List
> 
> LimboAPI
> ### Velocity Version
> 
> [3fe97fc](https://github.com/GemstoneGG/Velocity-CTD/commit/3fe97fc57d4e8c93d15aa1365acaed18ee5a804a)
> ### Additional Information
> 
> [Elytrium/LimboAPI#163](https://github.com/Elytrium/LimboAPI/issues/163)

Issue should be resolved in: https://github.com/GemstoneGG/Velocity-CTD/commit/b0794ca20e39af7a05a6f94f1285e77c0662d940

**Comment by Justiks1337** [comment]
Thanks, this has been fixed for both my plugins and LimboAPI!

**Comment by R00tB33rMan** [comment]
Awesome! Thanks for the report!
