### ISSUE TITLE
Incompatible with Ambasador (Forge 1.20.1)

### ISSUE THREAD

**Issue by 2lay** [GemstoneGG/Velocity-CTD#347]
### Expected Behavior

Connect to my Forge 1.20.1 server (All the Mods 9) with no issues whatsoever.

### Actual Behavior

I cannot connect to my server, stuck at "Encrypting..." and eventually "Timed out"

Logs:
```
[09:16:26 INFO]: [connected player] User (/redacted) has connected
[09:16:26 ERROR]: Terminating send to atm9 as User isn't connected yet.
[09:16:34 INFO]: [connected player] User (/redacted) has disconnected
```

### Steps:
1. Use my configs (I have attached two configs, ``velocity-normal.toml`` is my old config from the normal velocity that I got from Paper's website, everything worked fine. ``velocity-ctd.toml`` is my current config for this fork, where I cannot connect.
2. Join server
3. Error

I had to change the log extension from ``.toml`` to ``.toml.zip`` because GitHub doesn't support uploading ``.toml`` files, rename them to ``.toml``.

### Configurations:
* [velocity-normal.toml.zip](https://github.com/user-attachments/files/17540355/velocity-normal.toml.zip)
* [velocity-ctd.toml.zip](https://github.com/user-attachments/files/17540438/velocity-ctd.toml.zip)

### Plugin List

velocity, luckperms, miniplaceholders, signedvelocity, pooper, simpleproxychat

### Velocity Version

3.4.0-SNAPSHOT (git-109c79b3)

### Additional Information

Works fine on normal Velocity.

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> 
> Connect to my Forge 1.20.1 server (All the Mods 9) with no issues whatsoever.
> ### Actual Behavior
> 
> I cannot connect to my server, stuck at "Encrypting..." and eventually "Timed out"
> 
> Logs:
> 
> ```
> [09:16:26 INFO]: [connected player] User (/redacted) has connected
> [09:16:26 ERROR]: Terminating send to atm9 as User isn't connected yet.
> [09:16:34 INFO]: [connected player] User (/redacted) has disconnected
> ```
> 
> ### Steps to Reproduce
> ### Steps:
> 
>     1. Use my configs (I have attached two configs, `velocity-normal.toml` is my old config from the normal velocity that I got from Paper's website, everything worked fine. `velocity-ctd.toml` is my current config for this fork, where I cannot connect.
> 
>     2. Join server
> 
>     3. Error
> 
> 
> I had to change the log extension from `.toml` to `.toml.zip` because GitHub doesn't support uploading `.toml` files, rename them to `.toml`.
> ### Configurations:
> 
>     * [velocity-normal.toml.zip](https://github.com/user-attachments/files/17540355/velocity-normal.toml.zip)
> 
>     * [velocity-ctd.toml.zip](https://github.com/user-attachments/files/17540438/velocity-ctd.toml.zip)
> 
> 
> ### Plugin List
> 
> velocity, luckperms, miniplaceholders, signedvelocity, pooper, simpleproxychat
> ### Velocity Version
> 
> 3.4.0-SNAPSHOT (git-109c79b3)
> ### Additional Information
> 
> Works fine on normal Velocity.

Hey! Can you upload these elsewhere? Sadly my device is failing to read the files.

**Comment by 2lay** [comment]
Hey! Of course!
 
https://drive.google.com/drive/folders/1MqRHqV1TFfpTiz-Wx0i7tVLYc7KSpU1A?usp=drive_link

**Comment by R00tB33rMan** [comment]
> Hey! Of course!   https://drive.google.com/drive/folders/1MqRHqV1TFfpTiz-Wx0i7tVLYc7KSpU1A?usp=drive_link

Can you try setting the minimum version to 1.7.2 and removing:
`modern = { address = "100.100.1.1:25573", forwarding-mode = "MODERN" }`

**Comment by 2lay** [comment]
> > Hey! Of course!   https://drive.google.com/drive/folders/1MqRHqV1TFfpTiz-Wx0i7tVLYc7KSpU1A?usp=drive_link
> 
> Can you try setting the minimum version to 1.7.2 and removing: `modern = { address = "100.100.1.1:25573", forwarding-mode = "MODERN" }`

I tried it, still happens, one thing that I discovered is that if I join All the Mods 9 modpack to my All the Mods 9 server nothing happens, no connection, no logs on the ATM9 server. But if I connect with an incompatible client my connection gets sent to ATM9, and shows up in the logs but cannot join of course (I tried connecting with ATM10, but discovered this by accident.)

**Comment by R00tB33rMan** [comment]
> > > Hey! Of course!   https://drive.google.com/drive/folders/1MqRHqV1TFfpTiz-Wx0i7tVLYc7KSpU1A?usp=drive_link
> > 
> > 
> > Can you try setting the minimum version to 1.7.2 and removing: `modern = { address = "100.100.1.1:25573", forwarding-mode = "MODERN" }`
> 
> I tried it, still happens, one thing that I discovered is that if I join All the Mods 9 modpack to my All the Mods 9 server nothing happens, no connection, no logs on the ATM9 server. But if I connect with an incompatible client my connection gets sent to ATM9, and shows up in the logs but cannot join of course (I tried connecting with ATM10, but discovered this by accident.)

Understood. Mind attempting the very latest iteration of Velocity-CTD? I've applied a multitude of changes that could potentially resolve your issue.

**Comment by 2lay** [comment]
Everything is functioning well in the latest build of Velocity-CTD. Thank you for your work in maintaining this project, I appreciate it!
