### ISSUE TITLE
VelocityCTD does not work with Ambassador for forge on 1.20+

### ISSUE THREAD

**Issue by hardcorefactions** [GemstoneGG/Velocity-CTD#364]
### Expected Behavior

If you are using the Ambassador plugin on the proxy, it should work and let you join the forge server.

### Actual Behavior

It doesn't work and only works on the normal Velocity. It forces you to join the first server you have in the try section.

### Steps to Reproduce

1. Create a forge server with atleast 1 mod
2. Make a simple lobby server with no mods, running Paper for example.
3. Download Velocity-CTD, mount everything and put Ambassador.
4. Try to join, it won't work.

### Plugin List

Only Ambassador on the instance.

### Velocity Version

> velocity info
[12:20:30 INFO]: Velocity 3.4.0-SNAPSHOT (git-bf2f5d22)
[12:20:30 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[12:20:30 INFO]: discord.gg/beer - GitHub

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> If you are using the Ambassador plugin on the proxy, it should work and let you join the forge server.
> 
> ### Actual Behavior
> It doesn't work and only works on the normal Velocity. It forces you to join the first server you have in the try section.
> 
> ### Steps to Reproduce
> 1. Create a forge server with atleast 1 mod
> 2. Make a simple lobby server with no mods, running Paper for example.
> 3. Download Velocity-CTD, mount everything and put Ambassador.
> 4. Try to join, it won't work.
> 
> ### Plugin List
> Only Ambassador on the instance.
> 
> ### Velocity Version
> > velocity info
> > [12:20:30 INFO]: Velocity 3.4.0-SNAPSHOT (git-bf2f5d22)
> > [12:20:30 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
> > [12:20:30 INFO]: discord.gg/beer - GitHub
> 
> ### Additional Information
> _No response_

Can you provide logs and more information?

Let me know if you reproduce this in the latest published build after the 1.21.4 update. Thanks!
