### ISSUE TITLE
No output or action executing /hub when joined via a forced host

### ISSUE THREAD

**Issue by SnowzNZ** [GemstoneGG/Velocity-CTD#376]
### Expected Behavior

I expect /hub to send me to the "try" server set in the config.

### Actual Behavior

Nothing at all

### Steps to Reproduce

1. Join the server via a forced host.
2. Run /hub

### Plugin List

Plugins: ajqueue, limboapi, luckperms, maintenance, message, minimotd-velocity, nuvotifier, premiumvanish, proxy, snowstaffactivity, spark, tebex, velocitystaffchat

Though I have confirmed the same issue to be occurring on a fresh install.

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-dfeaea0c)
Copyright 2018-{2} {0}. {1} is licensed under the terms of the GNU General Public License v3.
discord.gg/beer - GitHub

**Comment by R00tB33rMan** [comment]
> ### Expected Behavior
> I expect /hub to send me to the "try" server set in the config.
> 
> ### Actual Behavior
> Nothing at all
> 
> ### Steps to Reproduce
> 1. Join the server via a forced host.
> 2. Run /hub
> 
> ### Plugin List
> Plugins: ajqueue, limboapi, luckperms, maintenance, message, minimotd-velocity, nuvotifier, premiumvanish, proxy, snowstaffactivity, spark, tebex, velocitystaffchat
> 
> Though I have confirmed the same issue to be occurring on a fresh install.
> 
> ### Velocity Version
> Velocity 3.4.0-SNAPSHOT (git-dfeaea0c) Copyright 2018-{2} {0}. {1} is licensed under the terms of the GNU General Public License v3. discord.gg/beer - GitHub
> 
> ### Additional Information
> _No response_

Judging by your snippet, it appears you did not regenerate your `messages.properties` (or entire `lang` folder). Can you do this for me and try again?

**Comment by SnowzNZ** [comment]
```
[14:24:31 INFO]: Plugins: velocity, ajqueue, limboapi, luckperms, message, minimotd-velocity, nuvotifier, premiumvanish, proxy, snowstaffactivity, spark, tebex, velocitystaffchat


[14:23:56 INFO]: Velocity 3.4.0-SNAPSHOT (git-b5e8a627)
[14:23:56 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[14:23:56 INFO]: discord.gg/beer - GitHub
```

**Comment by SnowzNZ** [comment]
Seems to be working now
