### ISSUE TITLE
Disconnect event doesn't call properly when a player leaves

### ISSUE THREAD

**Issue by MatinHQ** [GemstoneGG/Velocity-CTD#380]
### Expected Behavior

Disconnect even should call when player get disconnects

### Actual Behavior

Normal velocity output on quit:
```
[12:40:08 INFO]: [connected player] _NEZNAMY_ (/127.0.0.1:54711) has disconnected
[12:40:08 INFO]: [server connection] _NEZNAMY_ -> lobby has disconnected
```

CTD output:
```
[12:41:08 INFO]: [server connection] _NEZNAMY_ -> lobby has disconnected
```

### Steps to Reproduce

Check ticket-0366 for more detail and issues it's causing as it contains sensitive data for our server I can't share publicly

### Plugin List

Doesn't matter

### Velocity Version

Velocity 3.4.0-SNAPSHOT (git-11331d30)

**Comment by R00tB33rMan** [comment]
Confirm if this is fixed in the latest build!

**Comment by MatinHQ** [comment]
Will do thanks

**Comment by MatinHQ** [comment]
it's fixed
