### ISSUE TITLE
LeaveQueue

### ISSUE THREAD

**Issue by Zayedq7** [GemstoneGG/Velocity-CTD#397]
### Requested Feature

add a /leavequeue feature or if a player is queueing to a server and while queueing to that server he tries to queue into another server make him leave that queue and add him to the new queue since if the server is offline hes just gon be stuck in a queue he cant leave at all which makes it where he cant join any other server at all

### Why is this needed?

it makes it where he cant join any other server at all

### Alternative Solutions

make him leave the queue hes in and make him join the other queue he was tryna join

**Comment by R00tB33rMan** [comment]
> ### Requested Feature
> add a /leavequeue feature or if a player is queueing to a server and while queueing to that server he tries to queue into another server make him leave that queue and add him to the new queue since if the server is offline hes just gon be stuck in a queue he cant leave at all which makes it where he cant join any other server at all
> 
> ### Why is this needed?
> it makes it where he cant join any other server at all
> 
> ### Alternative Solutions
> make him leave the queue hes in and make him join the other queue he was tryna join
> 
> ### Additional Information
> _No response_

We already have a /leavequeue command. It's possible that you didn't apply the `velocity.queue.leave` permission to yourself or this user?

**Comment by Zayedq7** [comment]
oh then thats mb
