### ISSUE TITLE
Tooltip colors do not translate.

### ISSUE THREAD

**Issue by hardcorefactions** [GemstoneGG/Velocity-CTD#398]
### Expected Behavior

Tooltip should show colors, but it doesn't.

### Actual Behavior

Tooltip doesn't display colors

### Steps to Reproduce

1. Download Velocity-CTD
2. Run it
3. Check the player thingy
4. No colors!

### Plugin List

[16:42:19 INFO]: Plugins: velocity

### Velocity Version

[16:42:24 INFO]: Velocity 3.4.0-SNAPSHOT (git-c9ef23bd)
[16:42:24 INFO]: Copyright 2018-2024 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[16:42:24 INFO]: discord.gg/beer - GitHub

**Comment by hardcorefactions** [comment]
In adition
![image](https://github.com/user-attachments/assets/c3d73a72-1de0-4492-8332-ebb79294eb98)

**Comment by R00tB33rMan** [comment]
https://github.com/GemstoneGG/Velocity-CTD/commit/0589ac0ef46805da6fcbd3ac996f4b7ec7ad93c6

As indicated here. This value only supports legacy color codes. Sorry for the confusion!

> In adition ![image](https://private-user-images.githubusercontent.com/108526035/398585841-c3d73a72-1de0-4492-8332-ebb79294eb98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMzcxNzAsIm5iZiI6MTczNTIzNjg3MCwicGF0aCI6Ii8xMDg1MjYwMzUvMzk4NTg1ODQxLWMzZDczYTcyLTFkZTAtNDQ5Mi04MzMyLWViYjc5Mjk0ZWI5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxODE0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjc0ZjJmZDYwZTIzZmNlNjY0MzcwMjAzNjlkYzU0MjdhOTFiNzk1ZDA2NDQ4MmI5NGFjYmUxMDc3MzVjZDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n80w9oc2D_Le3xFkHp7J_lu84_KYjwDetArVFic8sko)
